### ISSUE TITLE
`Vite` and `log4js` incompatibility

### ISSUE THREAD

**Issue by Subzeero** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-2#122]
There appears to be an incompatibility between `Vite` and `log4js` that I faced when adding logging in #79; commit ea60c216f14f4719898d0466e0642753d07888d3.

`log4js` seems to be designed to run in backend-style setting since it relies on storing its configuration in `process.env()`, which `Vite` strips out. This results in a `ReferenceError: process is not defined` when trying to use `log4js`. The following issues may be a useful reference:

https://github.com/vitejs/vite/issues/1973
https://github.com/log4js-node/log4js-node/issues/1288
https://vitejs.dev/guide/env-and-mode

**Comment by LongQuanNguyen** [comment]
May be you could try to load the log config file first? Sorry for this, I thought I fixed it, this is so tiresome.

import { logConfig } from './path_to_log-config';
log4js.configure(logConfig);

**Comment by Subzeero** [comment]
I tried adding that to `main.tsx` before any of the React code runs, and it seems to resolve that issue.

Unfortunately, there is another one now:
```
Uncaught TypeError: require_util(...).inspect is not a function
    at createAppender (log4js.js?v=cf0f8299:1836:54)
    at getAppender (log4js.js?v=cf0f8299:1798:24)
    at log4js.js?v=cf0f8299:1867:11
    at Array.forEach (<anonymous>)
    at setup (log4js.js?v=cf0f8299:1865:37)
    at log4js.js?v=cf0f8299:728:39
    at Array.forEach (<anonymous>)
    at Object.configure (log4js.js?v=cf0f8299:728:17)
    at Object.configure (log4js.js?v=cf0f8299:2732:21)
    at main.tsx:8:8
```

Vite is also provides a warning: `Module "util" has been externalized for browser compatibility. Cannot access "util.inspect" in client code. See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.` This seems like another one of Vite's optimizations is conflicting with how log4js functions.

**Comment by LongQuanNguyen** [comment]
Arrrhhh, may need more paring to fix this. I will look up this issue and check out another logging framework in the meantime.

**Comment by Subzeero** [comment]
Note to deal with in this issue: `npm WARN deprecated @types/log4js@2.3.5: This is a stub types definition for log4js (https://github.com/nomiddlename/log4js-node). log4js provides its own type definitions, so you don't need @types/log4js installed!`

Discovered in #64.

**Comment by Subzeero** [comment]
From #146, comments to address within this issue:
- https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-2/pull/146#discussion_r1506985638
- https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-2/pull/146#discussion_r1506986054
- https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-2/pull/146#discussion_r1506986277
- https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-2/pull/146#discussion_r1506986684

**Comment by Subzeero** [comment]
Issue update: I’ve been researching replacements for log4js since I don’t believe there’s a robust way for us to make it work. Currently looking to a [Sentry](https://sentry.io/)-type platform that can listen for log reports from our deployed WebXR app. Firebase Crashlytics unfortunately doesn’t appear to have support for web apps, only native iOS/Android apps.

**Comment by Aesha7** [comment]
@Subzeero and I looked into these 3 platforms to replace log4js:

**1. Sentry** 
- free: for individual use 
- subscription: ($29/month for 50k events, unlimited members) 

**2. Rollbar** 
- free: 5k events, unlimited users 
- subscription: ($19/month for 25k events) 
- 50% discount for educational institute 

**3. BugSnag** 
- free: 7.5k events 
- subscription: ($20/month for 50k events, unlimited members) 

** all 3 have support for React integration

We are leaning towards using Rollbar since it is the easiest to integrate amongst the 3 and another team is also working with it with Dr. Osgood's approval.
