### ISSUE TITLE
Implement Smoke testing 

### ISSUE THREAD

**Issue by matthew-buglass** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-2#137]
We need some honest-to-goodness automated smoke testing. Dr. Osgood specified this explicitly in our meeting. This would involve some good thinking and creativity. Don't make perfect the enemy of good.

Ideas:
- Auto enhanced manual testing. buttons to trigger auto-test
- Can we not use Chrome extensions with a terminal?

Decision:
- Going to set up file debug loggers for action
- Create a debug environment for the application
- Run through a manual test with the internal states and action being logged through test hooks
- Run a bash script on merge to validate that the file is as expected
- We also nee to make sure the file was actually edited and the test was run on merge so that it can't be skipped.

**Comment by LongQuanNguyen** [comment]
@MitchWag01 had created a function to check whether a certain string is in a text file. If we could get the logger working, we could have the actions that needed to be tested to log into a text file; and have this function go and verify those actions are performed successfully.

With that being said, we are currently blocked by the #122
