### ISSUE TITLE
Need some updates or expansions on the ui design

### ISSUE THREAD

**Issue by matthew-buglass** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-2#139]
We need to refine this some more. 3D mockups? 
- Using tech to give an idea of perspective shifts. R can do that.
- Sketch it out

**Comment by Aesha7** [comment]
Here is the low-level Figma prototype: https://www.figma.com/file/iIwlISnFTGghFbtVxN14J5/UI-Prototype?type=design&node-id=0%3A1&mode=design&t=fZbRkhsvzJk9cUbO-1

I converted the designs into 3D modelling in space. 

Here is the high-level Vectary mockup: https://app.vectary.com/p/3NwHzem8nFk1l4xDXZV1su
