### ISSUE TITLE
Handle duplicate column headers on data load

### ISSUE THREAD

**Issue by matthew-buglass** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-2#171]
When loading data, it is reasonable to assume that we may have columns with duplicate data headers. This would cause look-up errors. We need to gracefully handle that instance, likely by appending characters to duplicate column names to differentiate them.

**Comment by trangnguyen3010** [comment]
already done in https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-2/pull/191
