### ISSUE TITLE
Devise a branching strategy 

### ISSUE THREAD

**Issue by matthew-buglass** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-2#2]
Plan how we want to branch our repo for development and versioning. 

Here is an article that describes a few [branching alternatives](https://www.abtasty.com/blog/git-branching-strategies/  )

**Comment by trangnguyen3010** [comment]
Draft doc: https://docs.google.com/document/d/1evBb86c2rw_otRbBB_HaNJuuAumIVmhbgCfdu-bJnlE/edit
Official doc: https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-2/wiki/Branching-Strategy
