### ISSUE TITLE
Improvements to build pipeline

### ISSUE THREAD

**Issue by Subzeero** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-2#57]
- Versions of checkout & setup-node actions are outdated. Need to be updated to v4.
- Prevent the build from running on pushes; only on pull requests.
- Add further automation & different environments: linting, deploying to Firebase, testing.
- Add dependency scanning for vulnerabilities.

**Comment by Subzeero** [comment]
Also look into Dependabot and preventing merges with security vulnerabilities.

**Comment by matthew-buglass** [comment]
Broke up into smaller cards.
