### ISSUE TITLE
Architecture Prototype 

### ISSUE THREAD

**Issue by matthew-buglass** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-2#7]
Design what information and interaction flow through the application will look like. If we aren't sure yet, we might need both a server-ed and server-less version of the design.

**Comment by trangnguyen3010** [comment]
heyy @matthew-buglass, what do we need for the architecture prototype? would it be like the system architecture diagram I created last week but more detailed (if so, how detailed should it be? down to React components?)

**Comment by trangnguyen3010** [comment]
@matthew-buglass 
I added the diagram and some details to Git Wiki with format of a Architecture Design Record!
https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-2/wiki/Architecture-Design-Records-(ADRs)

**Comment by matthew-buglass** [comment]
> @matthew-buglass I added the diagram and some details to Git Wiki with format of a Architecture Design Record! https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-2/wiki/Architecture-Design-Records-(ADRs)
> 
> I was thinking the data model that @Subzeero is working on can be represented as an ADR as well!

Looks awesome!
