### ISSUE TITLE
Configure logging

### ISSUE THREAD

**Issue by trangnguyen3010** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-2#73]
- Install and configure the file system logger.
- Create log directories to store log files.
- Log directories should be included in .gitignore.
- May consider different configs based on deployment environment (Testing or Production).

**Comment by matthew-buglass** [comment]
We will also need two different filesystem loggers. One for info logging and above, and the second for logging errors and above.

**Comment by LongQuanNguyen** [comment]
Did you mean one for Debug and Info, and the other for Warn, Error and Fatal?

**Comment by matthew-buglass** [comment]
Info file logger:
- Info
- Warn
- Error
- Fatal

Error file logger:
- Error
- Fatal
