### ISSUE TITLE
Design Component Diagram

### ISSUE THREAD

**Issue by matthew-buglass** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-2#75]
We need a more structured breakdown of what components we are going to need and where they go. This will describe the division of responsibility between React and WebXR, and with careful emphasis into how we are going to cache/store the data that is being rendered.

**Comment by LongQuanNguyen** [comment]
Update the diagram in wiki [,](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-2/wiki/Architecture-Design-Records-(ADRs)) still need more refinings.
