### ISSUE TITLE
Create Axis for 3D graph

### ISSUE THREAD

**Issue by Jesster2829** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-2#78]
# Requirements
The axis must be able to scale on input. By this I mean that the numbers on an axis *MUST* change depending on the range of values given, the highest point being 10 units of scale above the largest data point and lowest point being 10 below the smallest. 

----
 Dev member must keep in mind that this component must be used eventually with other components for the graph so keep compatibility in mind. 

## Nice to have 
The ability to change the field read from a csv file that the axis is representing.

**Comment by qpb948** [comment]
So I am creating a 3d axis that will scale based on input. Are the max and min separate inputs from the user or is it calculated when the csv is read, or do I calculate it in this issue? Is it supposed to take input from the csv file that is read to create the graph, which would then include the CSV loader that Tony created, or is that for future implementation?
