### ISSUE TITLE
Risk Estimation: ID 1

### ISSUE THREAD

**Issue by matthew-buglass** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-2#8]
We need to start laying out some risks that the project could face. Attributes to consider are:
- When in the production flow could this happen (earlier or later in the term)
- The severity if it were to occur
- The likelihood of occurrence
- Some ideas on mitigation/contingency planning and why they improve our risk exposure

**Comment by Aesha7** [comment]
Here's the list of 'Top 10 Risks' for Deliverable 1: https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-2/wiki/Risk-Plan-ID1
