### ISSUE TITLE
Creating Body For 3D Graph

### ISSUE THREAD

**Issue by Jesster2829** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-2#80]
# Requirements
WE need a cube component that can be made translucent, and moveable. By that I mean either by grabbing with the controllers or some sort of UI control pad, the user can rotate the graph and maybe move it around the space. 

----
Dev member must keep in mind that this component must be used eventually with other components for the graph so keep compatibility in mind.

---
### Nice to have

The ability for the user to increase the size of the graph through the same interaction format. ( I imagine this to be very difficult cause it would also have to communicate with the axis inside the graph at some point )

**Comment by matthew-buglass** [comment]
We have moved away from this approach due to how touch interactions work.
