### ISSUE TITLE
Artifact Inspection: Zander

### ISSUE THREAD

**Issue by matthew-buglass** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-2#88]
Running an official inspection of an artifact created by a team member

Author: @Subzeero 
Reader: @Aesha7 
Moderator/Recorder: @Jesster2829 
Inspector: @MitchWag01 

Artifact to be inspected:
#146

**Comment by Subzeero** [comment]
Completed, see https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-2/wiki/Artifact-Inspections#artifact-inspection-zander
